# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd2b65839b17681f187dfc441a70af689ca209305bc55b49b075beaa6a5582f142c3b9d50ae0b9c3059ed41bdf5969b145d4a018a079e39ce6138f0caa17c0c0

test:
  secret_key_base: cabf2ed80d80d52810e49c09fedd53736cc23086230ba356f1200f61590e6061810d214c94ff00e3a12cfd7aa95b8de7a7df00fbba265e9b4f0690d6f0efb048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
